apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels:
    app: nginx
    release: prom

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: "nginx"
  labels:
    app: nginx
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9113'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: pve.flerken.space:5000/nginxhw8
        imagePullPolicy: "IfNotPresent"
        ports:
          - name: web
            containerPort: 80
        # resources:
        #     limits:
        #       memory: 128Mi
        #       cpu: 500m
      - name: nginx-exporter
        image: 'nginx/nginx-prometheus-exporter:0.11.0'
        imagePullPolicy: "IfNotPresent"
        args:
          - '-nginx.scrape-uri=http://localhost/basic_status'
        # resources:
        #     limits:
        #       memory: 128Mi
        #       cpu: 500m
        ports:
          - containerPort: 9113

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: "nginx"
  labels:
    app: nginx
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9113'
    prometheus.io/scheme: http
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  - name: mon
    port: 8080
    protocol: TCP
    targetPort: 9113   
  selector:
   app: nginx