apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    key: webservice
spec:
  containers:
    - name: web
      image: pve.flerken.space:5000/web
      volumeMounts:
        - name: app
          mountPath: /app
  initContainers:
    - name: init-index-page
      image: busybox:1.31.0
      command: [ 'sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
